steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest',
        '.',
      ]
    images:
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'cloudrunservice'
    - '--image'
    - 'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest'
    - '--region'
    - 'europe-west3'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'