steps:
  # Builds the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest',
        '.',
      ]

  # Uploads the created image to GCP's container registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest']

  # Deploys the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'blog'
      - '--image'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/blog-repo/blog:latest'
