name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    # Environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Run Unit Tests
      run: npm run test:ci
